// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: cluster.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import { Empty, UUID } from './shared';

export const protobufPackage = 'event_store.cluster';

export interface GossipRequest {
  info: ClusterInfo | undefined;
  server: EndPoint | undefined;
}

export interface ViewChangeRequest {
  serverId: UUID | undefined;
  serverHttp: EndPoint | undefined;
  attemptedView: number;
}

export interface ViewChangeProofRequest {
  serverId: UUID | undefined;
  serverHttp: EndPoint | undefined;
  installedView: number;
}

export interface PrepareRequest {
  serverId: UUID | undefined;
  serverHttp: EndPoint | undefined;
  view: number;
}

export interface PrepareOkRequest {
  view: number;
  serverId: UUID | undefined;
  serverHttp: EndPoint | undefined;
  epochNumber: number;
  epochPosition: number;
  epochId: UUID | undefined;
  epochLeaderInstanceId: UUID | undefined;
  lastCommitPosition: number;
  writerCheckpoint: number;
  chaserCheckpoint: number;
  nodePriority: number;
  clusterInfo: ClusterInfo | undefined;
}

export interface ProposalRequest {
  serverId: UUID | undefined;
  serverHttp: EndPoint | undefined;
  leaderId: UUID | undefined;
  leaderHttp: EndPoint | undefined;
  view: number;
  epochNumber: number;
  epochPosition: number;
  epochId: UUID | undefined;
  epochLeaderInstanceId: UUID | undefined;
  lastCommitPosition: number;
  writerCheckpoint: number;
  chaserCheckpoint: number;
  nodePriority: number;
}

export interface AcceptRequest {
  serverId: UUID | undefined;
  serverHttp: EndPoint | undefined;
  leaderId: UUID | undefined;
  leaderHttp: EndPoint | undefined;
  view: number;
}

export interface LeaderIsResigningRequest {
  leaderId: UUID | undefined;
  leaderHttp: EndPoint | undefined;
}

export interface LeaderIsResigningOkRequest {
  leaderId: UUID | undefined;
  leaderHttp: EndPoint | undefined;
  serverId: UUID | undefined;
  serverHttp: EndPoint | undefined;
}

export interface ClusterInfo {
  members: MemberInfo[];
}

export interface EndPoint {
  address: string;
  port: number;
}

export interface MemberInfo {
  instanceId: UUID | undefined;
  timeStamp: number;
  state: MemberInfo_VNodeState;
  isAlive: boolean;
  httpEndPoint: EndPoint | undefined;
  internalTcp: EndPoint | undefined;
  externalTcp: EndPoint | undefined;
  internalTcpUsesTls: boolean;
  externalTcpUsesTls: boolean;
  lastCommitPosition: number;
  writerCheckpoint: number;
  chaserCheckpoint: number;
  epochPosition: number;
  epochNumber: number;
  epochId: UUID | undefined;
  nodePriority: number;
  isReadOnlyReplica: boolean;
  advertiseHostToClientAs: string;
  advertiseHttpPortToClientAs: number;
  advertiseTcpPortToClientAs: number;
  esVersion: string;
}

export enum MemberInfo_VNodeState {
  Initializing = 0,
  DiscoverLeader = 1,
  Unknown = 2,
  PreReplica = 3,
  CatchingUp = 4,
  Clone = 5,
  Follower = 6,
  PreLeader = 7,
  Leader = 8,
  Manager = 9,
  ShuttingDown = 10,
  Shutdown = 11,
  ReadOnlyLeaderless = 12,
  PreReadOnlyReplica = 13,
  ReadOnlyReplica = 14,
  ResigningLeader = 15,
  UNRECOGNIZED = -1,
}

export interface ReplicaLogWrite {
  logPosition: number;
  replicaId: Uint8Array;
}

export interface ReplicatedTo {
  logPosition: number;
}

export interface Epoch {
  epochPosition: number;
  epochNumber: number;
  epochId: Uint8Array;
}

export interface SubscribeReplica {
  logPosition: number;
  chunkId: Uint8Array;
  LastEpochs: Epoch[];
  ip: Uint8Array;
  port: number;
  leaderId: Uint8Array;
  subscriptionId: Uint8Array;
  isPromotable: boolean;
  version: number;
}

export interface ReplicaSubscriptionRetry {
  leaderId: Uint8Array;
  subscriptionId: Uint8Array;
}

export interface ReplicaSubscribed {
  leaderId: Uint8Array;
  subscriptionId: Uint8Array;
  subscriptionPosition: number;
}

export interface ReplicaLogPositionAck {
  subscriptionId: Uint8Array;
  replicationLogPosition: number;
  writerLogPosition: number;
}

export interface CreateChunk {
  leaderId: Uint8Array;
  subscriptionId: Uint8Array;
  chunkHeaderBytes: Uint8Array;
  fileSize: number;
  isScavengedChunk: boolean;
  transformHeaderBytes: Uint8Array;
}

export interface RawChunkBulk {
  leaderId: Uint8Array;
  subscriptionId: Uint8Array;
  chunkStartNumber: number;
  chunkEndNumber: number;
  rawPosition: number;
  rawBytes: Uint8Array;
  completeChunk: boolean;
}

export interface DataChunkBulk {
  leaderId: Uint8Array;
  subscriptionId: Uint8Array;
  chunkStartNumber: number;
  chunkEndNumber: number;
  subscriptionPosition: number;
  dataBytes: Uint8Array;
  completeChunk: boolean;
}

export interface FollowerAssignment {
  leaderId: Uint8Array;
  subscriptionId: Uint8Array;
}

export interface CloneAssignment {
  leaderId: Uint8Array;
  subscriptionId: Uint8Array;
}

export interface DropSubscription {
  leaderId: Uint8Array;
  subscriptionId: Uint8Array;
}

export const EVENT_STORE_CLUSTER_PACKAGE_NAME = 'event_store.cluster';

export interface GossipClient {
  update(request: GossipRequest): Observable<ClusterInfo>;

  read(request: Empty): Observable<ClusterInfo>;
}

export interface GossipController {
  update(
    request: GossipRequest,
  ): Promise<ClusterInfo> | Observable<ClusterInfo> | ClusterInfo;

  read(
    request: Empty,
  ): Promise<ClusterInfo> | Observable<ClusterInfo> | ClusterInfo;
}

export function GossipControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['update', 'read'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('Gossip', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('Gossip', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const GOSSIP_SERVICE_NAME = 'Gossip';

export interface ElectionsClient {
  viewChange(request: ViewChangeRequest): Observable<Empty>;

  viewChangeProof(request: ViewChangeProofRequest): Observable<Empty>;

  prepare(request: PrepareRequest): Observable<Empty>;

  prepareOk(request: PrepareOkRequest): Observable<Empty>;

  proposal(request: ProposalRequest): Observable<Empty>;

  accept(request: AcceptRequest): Observable<Empty>;

  leaderIsResigning(request: LeaderIsResigningRequest): Observable<Empty>;

  leaderIsResigningOk(request: LeaderIsResigningOkRequest): Observable<Empty>;
}

export interface ElectionsController {
  viewChange(
    request: ViewChangeRequest,
  ): Promise<Empty> | Observable<Empty> | Empty;

  viewChangeProof(
    request: ViewChangeProofRequest,
  ): Promise<Empty> | Observable<Empty> | Empty;

  prepare(request: PrepareRequest): Promise<Empty> | Observable<Empty> | Empty;

  prepareOk(
    request: PrepareOkRequest,
  ): Promise<Empty> | Observable<Empty> | Empty;

  proposal(
    request: ProposalRequest,
  ): Promise<Empty> | Observable<Empty> | Empty;

  accept(request: AcceptRequest): Promise<Empty> | Observable<Empty> | Empty;

  leaderIsResigning(
    request: LeaderIsResigningRequest,
  ): Promise<Empty> | Observable<Empty> | Empty;

  leaderIsResigningOk(
    request: LeaderIsResigningOkRequest,
  ): Promise<Empty> | Observable<Empty> | Empty;
}

export function ElectionsControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'viewChange',
      'viewChangeProof',
      'prepare',
      'prepareOk',
      'proposal',
      'accept',
      'leaderIsResigning',
      'leaderIsResigningOk',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('Elections', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('Elections', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const ELECTIONS_SERVICE_NAME = 'Elections';
