// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: projections.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import { Empty } from './shared';

export const protobufPackage = 'event_store.client.projections';

export interface CreateReq {
  options: CreateReq_Options | undefined;
}

export interface CreateReq_Options {
  oneTime?: Empty | undefined;
  transient?: CreateReq_Options_Transient | undefined;
  continuous?: CreateReq_Options_Continuous | undefined;
  query: string;
}

export interface CreateReq_Options_Transient {
  name: string;
}

export interface CreateReq_Options_Continuous {
  name: string;
  emitEnabled: boolean;
  trackEmittedStreams: boolean;
}

export interface CreateResp {}

export interface UpdateReq {
  options: UpdateReq_Options | undefined;
}

export interface UpdateReq_Options {
  name: string;
  query: string;
  emitEnabled?: boolean | undefined;
  noEmitOptions?: Empty | undefined;
}

export interface UpdateResp {}

export interface DeleteReq {
  options: DeleteReq_Options | undefined;
}

export interface DeleteReq_Options {
  name: string;
  deleteEmittedStreams: boolean;
  deleteStateStream: boolean;
  deleteCheckpointStream: boolean;
}

export interface DeleteResp {}

export interface StatisticsReq {
  options: StatisticsReq_Options | undefined;
}

export interface StatisticsReq_Options {
  name?: string | undefined;
  all?: Empty | undefined;
  transient?: Empty | undefined;
  continuous?: Empty | undefined;
  oneTime?: Empty | undefined;
}

export interface StatisticsResp {
  details: StatisticsResp_Details | undefined;
}

export interface StatisticsResp_Details {
  coreProcessingTime: number;
  version: number;
  epoch: number;
  effectiveName: string;
  writesInProgress: number;
  readsInProgress: number;
  partitionsCached: number;
  status: string;
  stateReason: string;
  name: string;
  mode: string;
  position: string;
  progress: number;
  lastCheckpoint: string;
  eventsProcessedAfterRestart: number;
  checkpointStatus: string;
  bufferedEvents: number;
  writePendingEventsBeforeCheckpoint: number;
  writePendingEventsAfterCheckpoint: number;
}

export interface StateReq {
  options: StateReq_Options | undefined;
}

export interface StateReq_Options {
  name: string;
  partition: string;
}

export interface StateResp {
  state: any | undefined;
}

export interface ResultReq {
  options: ResultReq_Options | undefined;
}

export interface ResultReq_Options {
  name: string;
  partition: string;
}

export interface ResultResp {
  result: any | undefined;
}

export interface ResetReq {
  options: ResetReq_Options | undefined;
}

export interface ResetReq_Options {
  name: string;
  writeCheckpoint: boolean;
}

export interface ResetResp {}

export interface EnableReq {
  options: EnableReq_Options | undefined;
}

export interface EnableReq_Options {
  name: string;
}

export interface EnableResp {}

export interface DisableReq {
  options: DisableReq_Options | undefined;
}

export interface DisableReq_Options {
  name: string;
  writeCheckpoint: boolean;
}

export interface DisableResp {}

export const EVENT_STORE_CLIENT_PROJECTIONS_PACKAGE_NAME =
  'event_store.client.projections';

export interface ProjectionsClient {
  create(request: CreateReq): Observable<CreateResp>;

  update(request: UpdateReq): Observable<UpdateResp>;

  delete(request: DeleteReq): Observable<DeleteResp>;

  statistics(request: StatisticsReq): Observable<StatisticsResp>;

  disable(request: DisableReq): Observable<DisableResp>;

  enable(request: EnableReq): Observable<EnableResp>;

  reset(request: ResetReq): Observable<ResetResp>;

  state(request: StateReq): Observable<StateResp>;

  result(request: ResultReq): Observable<ResultResp>;

  restartSubsystem(request: Empty): Observable<Empty>;
}

export interface ProjectionsController {
  create(
    request: CreateReq,
  ): Promise<CreateResp> | Observable<CreateResp> | CreateResp;

  update(
    request: UpdateReq,
  ): Promise<UpdateResp> | Observable<UpdateResp> | UpdateResp;

  delete(
    request: DeleteReq,
  ): Promise<DeleteResp> | Observable<DeleteResp> | DeleteResp;

  statistics(request: StatisticsReq): Observable<StatisticsResp>;

  disable(
    request: DisableReq,
  ): Promise<DisableResp> | Observable<DisableResp> | DisableResp;

  enable(
    request: EnableReq,
  ): Promise<EnableResp> | Observable<EnableResp> | EnableResp;

  reset(
    request: ResetReq,
  ): Promise<ResetResp> | Observable<ResetResp> | ResetResp;

  state(
    request: StateReq,
  ): Promise<StateResp> | Observable<StateResp> | StateResp;

  result(
    request: ResultReq,
  ): Promise<ResultResp> | Observable<ResultResp> | ResultResp;

  restartSubsystem(request: Empty): Promise<Empty> | Observable<Empty> | Empty;
}

export function ProjectionsControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'create',
      'update',
      'delete',
      'statistics',
      'disable',
      'enable',
      'reset',
      'state',
      'result',
      'restartSubsystem',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('Projections', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('Projections', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const PROJECTIONS_SERVICE_NAME = 'Projections';
