// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: redaction.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import { StreamIdentifier } from './shared';

export const protobufPackage = 'kurrent.client.redaction';

export interface GetEventPositionReq {
  streamIdentifier: StreamIdentifier | undefined;
  streamRevision: number;
}

export interface GetEventPositionResp {
  eventPositions: EventPosition[];
}

export interface EventPosition {
  logPosition: number;
  chunkInfo: ChunkInfo | undefined;
}

export interface ChunkInfo {
  fileName: string;
  version: number;
  isComplete: boolean;
  eventOffset: number;
}

export interface SwitchChunkReq {
  targetChunkFile: string;
  newChunkFile: string;
}

export interface SwitchChunkResp {}

export const KURRENT_CLIENT_REDACTION_PACKAGE_NAME = 'kurrent.client.redaction';

export interface RedactionClient {
  getEventPositions(
    request: Observable<GetEventPositionReq>,
  ): Observable<GetEventPositionResp>;

  switchChunks(
    request: Observable<SwitchChunkReq>,
  ): Observable<SwitchChunkResp>;
}

export interface RedactionController {
  getEventPositions(
    request: Observable<GetEventPositionReq>,
  ): Observable<GetEventPositionResp>;

  switchChunks(
    request: Observable<SwitchChunkReq>,
  ): Observable<SwitchChunkResp>;
}

export function RedactionControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('Redaction', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = ['getEventPositions', 'switchChunks'];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('Redaction', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const REDACTION_SERVICE_NAME = 'Redaction';
