// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: serverfeatures.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import { Empty } from './shared';

export const protobufPackage = 'event_store.client.server_features';

export interface SupportedMethods {
  methods: SupportedMethod[];
  eventStoreServerVersion: string;
}

export interface SupportedMethod {
  methodName: string;
  serviceName: string;
  features: string[];
}

export const EVENT_STORE_CLIENT_SERVER_FEATURES_PACKAGE_NAME =
  'event_store.client.server_features';

export interface ServerFeaturesClient {
  getSupportedMethods(request: Empty): Observable<SupportedMethods>;
}

export interface ServerFeaturesController {
  getSupportedMethods(
    request: Empty,
  ):
    | Promise<SupportedMethods>
    | Observable<SupportedMethods>
    | SupportedMethods;
}

export function ServerFeaturesControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['getSupportedMethods'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('ServerFeatures', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('ServerFeatures', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const SERVER_FEATURES_SERVICE_NAME = 'ServerFeatures';
