// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: users.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'event_store.client.users';

export interface CreateReq {
  options: CreateReq_Options | undefined;
}

export interface CreateReq_Options {
  loginName: string;
  password: string;
  fullName: string;
  groups: string[];
}

export interface CreateResp {}

export interface UpdateReq {
  options: UpdateReq_Options | undefined;
}

export interface UpdateReq_Options {
  loginName: string;
  password: string;
  fullName: string;
  groups: string[];
}

export interface UpdateResp {}

export interface DeleteReq {
  options: DeleteReq_Options | undefined;
}

export interface DeleteReq_Options {
  loginName: string;
}

export interface DeleteResp {}

export interface EnableReq {
  options: EnableReq_Options | undefined;
}

export interface EnableReq_Options {
  loginName: string;
}

export interface EnableResp {}

export interface DisableReq {
  options: DisableReq_Options | undefined;
}

export interface DisableReq_Options {
  loginName: string;
}

export interface DisableResp {}

export interface DetailsReq {
  options: DetailsReq_Options | undefined;
}

export interface DetailsReq_Options {
  loginName: string;
}

export interface DetailsResp {
  userDetails: DetailsResp_UserDetails | undefined;
}

export interface DetailsResp_UserDetails {
  loginName: string;
  fullName: string;
  groups: string[];
  lastUpdated: DetailsResp_UserDetails_DateTime | undefined;
  disabled: boolean;
}

export interface DetailsResp_UserDetails_DateTime {
  ticksSinceEpoch: number;
}

export interface ChangePasswordReq {
  options: ChangePasswordReq_Options | undefined;
}

export interface ChangePasswordReq_Options {
  loginName: string;
  currentPassword: string;
  newPassword: string;
}

export interface ChangePasswordResp {}

export interface ResetPasswordReq {
  options: ResetPasswordReq_Options | undefined;
}

export interface ResetPasswordReq_Options {
  loginName: string;
  newPassword: string;
}

export interface ResetPasswordResp {}

export const EVENT_STORE_CLIENT_USERS_PACKAGE_NAME = 'event_store.client.users';

export interface UsersClient {
  create(request: CreateReq): Observable<CreateResp>;

  update(request: UpdateReq): Observable<UpdateResp>;

  delete(request: DeleteReq): Observable<DeleteResp>;

  disable(request: DisableReq): Observable<DisableResp>;

  enable(request: EnableReq): Observable<EnableResp>;

  details(request: DetailsReq): Observable<DetailsResp>;

  changePassword(request: ChangePasswordReq): Observable<ChangePasswordResp>;

  resetPassword(request: ResetPasswordReq): Observable<ResetPasswordResp>;
}

export interface UsersController {
  create(
    request: CreateReq,
  ): Promise<CreateResp> | Observable<CreateResp> | CreateResp;

  update(
    request: UpdateReq,
  ): Promise<UpdateResp> | Observable<UpdateResp> | UpdateResp;

  delete(
    request: DeleteReq,
  ): Promise<DeleteResp> | Observable<DeleteResp> | DeleteResp;

  disable(
    request: DisableReq,
  ): Promise<DisableResp> | Observable<DisableResp> | DisableResp;

  enable(
    request: EnableReq,
  ): Promise<EnableResp> | Observable<EnableResp> | EnableResp;

  details(request: DetailsReq): Observable<DetailsResp>;

  changePassword(
    request: ChangePasswordReq,
  ):
    | Promise<ChangePasswordResp>
    | Observable<ChangePasswordResp>
    | ChangePasswordResp;

  resetPassword(
    request: ResetPasswordReq,
  ):
    | Promise<ResetPasswordResp>
    | Observable<ResetPasswordResp>
    | ResetPasswordResp;
}

export function UsersControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'create',
      'update',
      'delete',
      'disable',
      'enable',
      'details',
      'changePassword',
      'resetPassword',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('Users', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('Users', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const USERS_SERVICE_NAME = 'Users';
